name: Java Maven TestNG CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java environment
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Specify the Java version you need
          distribution: 'adoptopenjdk'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install dependencies and run tests with Maven
      - name: Build with Maven and run tests
        run: mvn clean install

      # Step 5: Upload test results (Optional but helpful)
      - name: Upload TestNG results
        uses: actions/upload-artifact@v4
        with:
          name: testng-results
          path: target/test-classes/testng-results.xml
